<?php

declare(strict_types=1);

namespace App\Presenters;

use App\Core\ContactModel;
use App\Core\LocationsModel;
use App\Core\MeetingModel;
use BasePresenter;
use Nette;
use App\Core\UsersModel;
use Vodacek\Forms\Controls\DateInput;

final class UsersPresenter extends BasePresenter
{
    /** @var Users @inject */
    private $users;

    /** @var LocationsModel @inject */
    private $locations;


    /** @var ContactModel @inject */
    private $contact;

    /** @var MeetingModel @inject */
    private $meetings;

    function __construct(UsersModel $users, LocationsModel $locations, ContactModel $contact, MeetingModel $meetings)
    {
        $this->users = $users;
        $this->locations = $locations;
        $this->contact = $contact;
        $this->meetings = $meetings;
    }

    public function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub

        $this->template->users = $this->users->getUsers();
    }

    protected function createComponentEditPersonForm(): Nette\Application\UI\Form {
        $form = new Nette\Application\UI\Form;
            $form->addText('nickname', 'Nickname')->setRequired('Zadejte prosím přezdívku');
            $form->addText('last_name','Last name')->setRequired('Zadejte prosím příjmení');
            $form->addText('first_name','First name')->setRequired('Zadejte prosím křestní jméno');
            $form->addSelect('id_location', 'Location', array_reduce(
                $this->locations->getLocations(),
                function($arr, $loc){
                    $arr[$loc->id] = $loc->name;
                    return $arr;}
                    ));
            $form['birth_day'] = new DateInput('Birth name', DateInput::TYPE_DATE);
            $form['birth_day']->setRequired('Zadejte prosím datum narození');
            $form->addSelect('gender','Genger', [
                'male'=>'Muž',
                'female'=>'Žena'
            ]);
            $form->addInteger('height','Výška');
            $id = $this->getParameter('id');
            if ($id !== null) {
                $person = $this->users->getUser($id);
                $form['nickname']->setDefaultValue($person->nickname);
                $form['first_name']->setDefaultValue($person->firstName);
                $form['last_name']->setDefaultValue($person->lastName);
                $form['id_location']->setDefaultValue($person->idLocation);
                $form['birth_day']->setDefaultValue($person->birthDay);
                $form['gender']->setDefaultValue($person->gender);
                $form['height']->setDefaultValue($person->height);
                $form->addSubmit('odeslat','Upravit osobu');
            } else {
                $form->addSubmit('odeslat','Vytvořit osobu');
            }
        $form->onSuccess[] = [$this, 'editPersonFormSuceeded'];
        return $form;
    }

    public function editPersonFormSuceeded(Nette\Application\UI\Form $form, \stdClass $values) {
        $id = $this->getParameter('id');
        if($id!== null) {
            $this->users->editUser(new \Person((array) $values, $id));
        } else {
            $this->users->addUser(new \Person((array) $values));
        }
        $this->flashMessage('Formulář byl úspěšně odeslán');
        $this->redirect('Users:default');
    }

    private function loadUser($id) {
        $this->template->usr = $this->users->getUser((int) $id);
        $this->template->contacts = $this->contact->getContactsByPersonId((int) $id);
        $meetings = $this->meetings->getMeetingsByPersonId((int) $id);
        $this->template->meetings = $meetings;
        $locations = $this->locations->getLocationsByIds(array_map(function ($item) {
            return $item->idLocation;
        }, $meetings));
        $this->template->locations = $locations;
    }

    function actionEditor($id): void {
        $this->loadUser($id);
    }
    function actionDetail($id): void {
        $this->loadUser($id);
    }
}
